export const categoryOptions = [
	{ key: 'bricolage', label: 'Bricolage' },
	{ key: 'informatique', label: 'Informatique' },
	{ key: 'jardinage', label: 'Jardinage' },
	{ key: 'garde', label: 'Garde' },
	{ key: 'transport', label: 'Transport' },
	{ key: 'cours', label: 'Cours / Education' },
	{ key: 'menage', label: 'Aide - Ménagère' },
	{ key: 'administratif', label: 'Démarches administratives' },
	{ key: 'autre', label: 'Autre' },
];

const catalogCardTemplates = [
	{
		title: 'Besoin d’un coup de main pour un déménagement',
		description:
			'Je cherche quelques personnes pour m’aider à porter des cartons, démonter un lit et transporter quelques meubles.',
		location: '13008, Marseille',
		authorName: 'Le T',
		authorAvatar: '/images/leT.jpg',
		rating: '4,5',
		reviews: 1,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'DÉMÉNAGEMENT', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'MÉNAGE', className: 'bg-[#F4A261] text-white' },
		],
		points: '3 PTS',
		categoryKey: 'transport',
		distance: 5,
		urgent: false,
		sortRank: 12,
	},
	{
		title: 'Aide pour préparer un potager',
		description:
			'Je cherche quelqu’un pour retourner la terre, installer quelques bacs et planter les premières pousses.',
		location: '13009, Marseille',
		authorName: 'Roxane',
		authorAvatar: '/images/Roxane.jpeg',
		rating: '4,8',
		reviews: 3,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'JARDINAGE', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'URGENT', className: 'bg-[#E76F51] text-white' },
		],
		points: '2 PTS',
		categoryKey: 'jardinage',
		distance: 10,
		urgent: true,
		sortRank: 11,
	},
	{
		title: 'Besoin d’aide pour monter un meuble',
		description:
			'Je viens de recevoir un bureau et une étagère en kit. Il me faut une personne patiente pour le montage.',
		location: '13006, Marseille',
		authorName: 'Le T',
		authorAvatar: '/images/leT.jpg',
		rating: '4,9',
		reviews: 5,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'BRICOLAGE', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'URGENT', className: 'bg-[#E76F51] text-white' },
		],
		points: '4 PTS',
		categoryKey: 'bricolage',
		distance: 2,
		urgent: true,
		sortRank: 10,
	},
	{
		title: 'Cours d’informatique pour débutant',
		description:
			'Je cherche quelqu’un pour m’aider à prendre en main mon ordinateur, organiser mes fichiers et utiliser les services en ligne.',
		location: '13005, Marseille',
		authorName: 'Roxane',
		authorAvatar: '/images/Roxane.jpeg',
		rating: '4,5',
		reviews: 1,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'INFORMATIQUE', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'COURS', className: 'bg-[#8F9BF7] text-white' },
		],
		points: '6 PTS',
		categoryKey: 'informatique',
		distance: 15,
		urgent: false,
		sortRank: 9,
	},
	{
		title: 'Aide pour une garde ponctuelle',
		description:
			'Je cherche une personne de confiance pour garder un enfant en fin d’après-midi et l’aider à faire ses devoirs.',
		location: '13004, Marseille',
		authorName: 'Le T',
		authorAvatar: '/images/leT.jpg',
		rating: '4,7',
		reviews: 2,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'GARDE', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'AUTRE', className: 'bg-[#8F9BF7] text-white' },
		],
		points: '5 PTS',
		categoryKey: 'garde',
		distance: 8,
		urgent: false,
		sortRank: 8,
	},
	{
		title: 'Transport de quelques cartons',
		description:
			'Je dois déplacer une dizaine de cartons d’un appartement à un autre à quelques rues de distance.',
		location: '13001, Marseille',
		authorName: 'Roxane',
		authorAvatar: '/images/Roxane.jpeg',
		rating: '4,6',
		reviews: 4,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'TRANSPORT', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'DÉMÉNAGEMENT', className: 'bg-[#F4A261] text-white' },
		],
		points: '1 PT',
		categoryKey: 'transport',
		distance: 25,
		urgent: false,
		sortRank: 7,
	},
	{
		title: 'Aide aux démarches administratives',
		description:
			'Je cherche quelqu’un pour m’aider à comprendre mes documents, remplir un formulaire et organiser mes pièces.',
		location: '13010, Marseille',
		authorName: 'Le T',
		authorAvatar: '/images/leT.jpg',
		rating: '5,0',
		reviews: 2,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'ADMINISTRATIF', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'COURS', className: 'bg-[#8F9BF7] text-white' },
		],
		points: '2 PTS',
		categoryKey: 'administratif',
		distance: 12,
		urgent: false,
		sortRank: 6,
	},
	{
		title: 'Besoin d’un coup de main pour la cuisine',
		description:
			'J’organise un repas pour plusieurs personnes et j’aurais besoin d’aide pour préparer les plats et dresser la table.',
		location: '13003, Marseille',
		authorName: 'Roxane',
		authorAvatar: '/images/Roxane.jpeg',
		rating: '4,5',
		reviews: 1,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'AUTRE', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'MÉNAGE', className: 'bg-[#F4A261] text-white' },
		],
		points: '4 PTS',
		categoryKey: 'autre',
		distance: 30,
		urgent: false,
		sortRank: 5,
	},
	{
		title: 'Petit chantier de jardin en urgence',
		description:
			'Je dois nettoyer un coin de jardin, déplacer quelques sacs de terre et remettre le tout en état rapidement.',
		location: '13011, Marseille',
		authorName: 'Le T',
		authorAvatar: '/images/leT.jpg',
		rating: '4,4',
		reviews: 1,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'JARDINAGE', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'URGENT', className: 'bg-[#E76F51] text-white' },
		],
		points: '3 PTS',
		categoryKey: 'jardinage',
		distance: 5,
		urgent: true,
		sortRank: 4,
	},
	{
		title: 'Atelier informatique pour trier des documents',
		description:
			'Je cherche quelqu’un de patient pour classer des fichiers, scanner quelques papiers et organiser mon espace de travail.',
		location: '13012, Marseille',
		authorName: 'Roxane',
		authorAvatar: '/images/Roxane.jpeg',
		rating: '4,9',
		reviews: 4,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'INFORMATIQUE', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'COURS', className: 'bg-[#8F9BF7] text-white' },
		],
		points: '2 PTS',
		categoryKey: 'informatique',
		distance: 14,
		urgent: false,
		sortRank: 3,
	},
	{
		title: 'Petit tri de cartons avant déménagement',
		description:
			'J’ai besoin d’aide pour organiser quelques cartons, identifier ce qui part au transport et préparer le reste.',
		location: '13015, Marseille',
		authorName: 'Roxane',
		authorAvatar: '/images/Roxane.jpeg',
		rating: '4,7',
		reviews: 2,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'TRANSPORT', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'DÉMÉNAGEMENT', className: 'bg-[#F4A261] text-white' },
		],
		points: '3 PTS',
		categoryKey: 'transport',
		distance: 18,
		urgent: false,
		sortRank: 2,
	},
	{
		title: 'Aide rapide pour un dossier administratif',
		description:
			'Je dois remplir un dossier, vérifier les pièces et imprimer les documents manquants avant la fin de semaine.',
		location: '13016, Marseille',
		authorName: 'Roxane',
		authorAvatar: '/images/Roxane.jpeg',
		rating: '5,0',
		reviews: 1,
		image: '/images/photos-login.webp',
		categories: [
			{ label: 'ADMINISTRATIF', className: 'bg-[#4E4E4E] text-white' },
			{ label: 'URGENT', className: 'bg-[#E76F51] text-white' },
		],
		points: '1 PT',
		categoryKey: 'administratif',
		distance: 9,
		urgent: true,
		sortRank: 1,
	},
];

export const catalogCards = Array.from({ length: 7 }, (_, pageIndex) =>
	catalogCardTemplates.map((card, cardIndex) => ({
		...card,
		title: `${card.title} ${pageIndex + 1}-${cardIndex + 1}`,
		sortRank: card.sortRank + (6 - pageIndex) * 10,
	}))
).flat();